name: manual-trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy on'
        required: true
        type: environment
permissions:
  issues: write
  contents: read
  pages: write 
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: trstringer/manual-approval@v1
      with:
       secret: ${{ github.TOKEN }}
       approvers: MirzaJunaid96
       minimum-approvals: 1
       issue-title: "Deploying v1.3.5 to prod from staging"
       ISSUE_BODY: "Please approve or deny the deployment of version v1.3.5."
        
    # - name: Check if issue is approved
    #   if: github.event.issue.pull_request && contains(github.event.comment.body, '/approve')
    #   run: |
    #       ISSUE_BODY=$(curl -s -H "Authorization: token ${{ secrets.github.TOKEN }}" \
    #                    -H "Accept: application/vnd.github.v3+json" \
    #                    ${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.body')
    #       echo "Approved Issue Body: $ISSUE_BODY"
    

    - name: Get Issue Body
      id: get_issue_body
      run: |
          issue_number=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"title": "Deploying v1.3.5 to prod from staging", "body": "Please approve or deny the deployment of version v1.3.5."}' https://api.github.com/repos/${{ github.repository }}/issues | jq -r '.number')
          issue_body=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${issue_number} | jq -r '.body')
          echo "::set-output name=issue_body::$issue_body"
   
    - name: Deploy to environment
      run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
