name: Generate New Password
on:
   push:
   pull_request:
     branches:
     - master
   workflow_dispatch:
jobs:
  our-job:
   runs-on: ubuntu-latest
   steps: 
     - uses: actions/checkout@v2
       #env:
        #USER_EMAIL: ${{ secrets.USER_EMAIL }}
     - id: generatedpassword
       uses: Ba4bes/Password-Generator@v0.1
     - run: echo "${{ steps.generatedpassword.outputs.password }}"
       shell: bash
     - uses: actions/setup-node@v3
       with:
        node-version: 14
     - run: |
        npm install
        npm build 
        npm secrete:update-password
